### ISSUE TITLE
Listening to CMI events (LMSFinish, LMSCommit)

### ISSUE THREAD

**Issue by erksdee** [NemoStein/scormint#1]
Hi @NemoStein,

How are we able to listen to the SCORM CMI events (LMSFinish, LMSCommit) so we can talk to our backend systems (Saving scorm data) ?

**Comment by NemoStein** [comment]
This package is a client-side implementation of SCORM standard that interfaces with the LMS.
The implementation of the server-side API is left to the LMS to handle.
How are you using this package (could you provide a use-case)?
